import type { Solution } from './solutions'

// Industries and B2B, "Cum alegi…" guides and project checklists — the
// same template as the profession stories in lib/solutions.ts.

const TEAM = 'Echipa tehnică Zona Scule'
const OFFER = { kind: 'cta' as const, label: 'Cere o ofertă', href: '/contact' }

export const MORE_SOLUTIONS: Solution[] = [
  // ══ Industrii și B2B ═══════════════════════════════════════════════════════
  {
    slug: 'scule-industria-auto-linii-asamblare',
    type: 'meserie',
    featured: true,
    profession: 'Industria auto',
    domain: 'Linii de asamblare auto',
    headline: 'Cuplul corect la fiecare șurub, la fiecare tact.',
    excerpt: 'Scule de asamblare, cuplu controlat, pneumatice, abrazive de finisaj și protecție pentru liniile de producție auto — la 15 minute de platforma industrială Mioveni.',
    metaTitle: 'Scule pentru linii de asamblare auto — Mioveni, Argeș | Zona Scule',
    metaDescription: 'Scule pentru industria auto din Argeș: chei dinamometrice, antrenoare, biți, înșurubătoare, scule pneumatice, abrazive de finisaj și echipament de protecție pentru liniile de asamblare de la Mioveni.',
    sections: [
      {
        kind: 'intro',
        lead: 'Pe o linie de asamblare, o sculă nu e un obiect — e o stație de lucru care trebuie să facă aceeași mișcare de mii de ori pe tură, la același cuplu, fără să obosească operatorul. Suntem în Pitești, la 15 minute de uzina Dacia de la Mioveni și de parcul ei de furnizori: livrăm rapid, înlocuim rapid, și putem veni să vedem stația înainte să recomandăm.',
        steps: [
          { title: 'Cuplu repetabil', text: 'Chei dinamometrice și antrenoare pentru îmbinări critice, verificate și reglate la valoarea din fișa de lucru.' },
          { title: 'Ergonomie la tact', text: 'Înșurubătoare cu acumulator și scule pneumatice ușoare, echilibrate pentru mii de cicluri pe tură.' },
          { title: 'Finisaj și protecție', text: 'Abrazive pentru retușuri, protecție pentru ochi, auz și mâini, organizare la stație.' },
        ],
      },
      { kind: 'carousel', title: 'Antrenoare și chei tubulare', text: 'Clichete cu pas fin și tubulare scurte, lungi și de impact.', subs: ['Antrenoare cu clichet', 'Chei tubulare'] },
      { kind: 'carousel', title: 'Chei dinamometrice', text: 'Pentru îmbinările la care cuplul se verifică, nu se ghicește.', subs: ['Chei dinamometrice'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Biți și adaptoare', text: 'Torsion, impact și adaptoare — consumabile de linie, pe stoc.', subs: ['Biți și adaptoare', 'Capete de șurubelniță', 'Seturi de capete de șurubelniță'] },
      { kind: 'carousel', title: 'Înșurubare cu acumulator', text: 'Înșurubătoare cu impact și mașini de găurit-înșurubat, cu motoare fără perii.', subs: ['Șurubelnițe cu impact cu acumulator', 'Maşini de găurit/înşurubat cu acumulator', 'Scule electrice cu motor fără perii'] },
      { kind: 'tip', text: 'Pe stațiile cu cuplu critic, cheia dinamometrică se verifică periodic, iar la schimbarea valorii se reglează întâi la maxim și abia apoi coboară la valoarea nouă — altfel arcul memorează și cuplul derivă.', by: TEAM },
      { kind: 'carousel', title: 'Scule pneumatice', text: 'Polizoare și unelte cu aer comprimat pentru stațiile alimentate de rețeaua de aer.', subs: ['Unelte cu Aer Comprimat', 'Polizoare Pneumatice'] },
      { kind: 'carousel', title: 'Abrazive pentru finisaj și retuș', text: 'Discuri cu velcro, foi și nețesute, lustruire — pentru retușuri de suprafață.', subs: ['Discuri cu Velcro', 'Foi abrazive', 'Abrazive Nețesute', 'Discuri de lustruit', 'Paste de Lustruit'] },
      { kind: 'carousel', title: 'Protecție la stație', text: 'Ochelari, antifoane, mănuși și încălțăminte de protecție.', subs: ['Protecția ochilor', 'Protecție auditivă', 'Mănuși de protecție', 'Încălțăminte'] },
      { kind: 'carousel', title: 'Organizare la stație', text: 'Dulapuri, cărucioare și cutii de transport — fiecare sculă la locul ei.', subs: ['TOOLGUARD™ Sistem de depozitare metalic', 'Cutii de transport'] },
      { ...OFFER, title: 'Echipăm o stație sau o linie întreagă', text: 'Trimite-ne lista de scule sau fișa stației — revenim cu ofertă, termene și variante echivalente. Pentru volume, contracte-cadru cu livrare programată.' },
      {
        kind: 'faq',
        items: [
          { q: 'Livrați în zona Mioveni?', a: 'Da. Suntem în Pitești, pe Strada Sfânta Vineri 28, la aproximativ 15 minute de platforma industrială Mioveni — livrăm direct la poartă sau puteți ridica din magazin.' },
          { q: 'Puteți oferi aceeași sculă de la mai mulți producători?', a: 'Da — lucrăm cu Bosch, Milwaukee, PFERD, Kärcher, Ruko și alți producători, așa că putem propune echivalente când un cod lipsește sau are termen lung.' },
          { q: 'Lucrați pe contract-cadru?', a: 'Da. Pentru consumabile (biți, abrazive, protecție) propunem stoc dedicat și livrări programate, cu prețuri stabilite pe perioada contractului.' },
        ],
      },
    ],
  },
  // ── Industria auto: sub-stories, one need of the line each ──────────────
  {
    slug: 'cuplu-controlat-linia-de-asamblare',
    type: 'ghid',
    parent: 'scule-industria-auto-linii-asamblare',
    profession: 'Cuplu controlat',
    title: 'Cuplul controlat pe linia de asamblare',
    domain: 'Industria auto · îmbinări',
    headline: 'Aceeași valoare la fiecare șurub, verificabilă oricând.',
    excerpt: 'Chei dinamometrice, antrenoare cu clichet și tubulare pentru îmbinările la care cuplul se măsoară — plus cum le păstrezi precise pe tură.',
    metaTitle: 'Cuplu controlat pe linia de asamblare auto — chei dinamometrice | Zona Scule',
    metaDescription: 'Chei dinamometrice, antrenoare cu clichet, tubulare și chei imbus/torx pentru îmbinări cu cuplu controlat în industria auto, cu sfaturi de reglaj și verificare.',
    sections: [
      {
        kind: 'intro',
        lead: 'Pe o îmbinare critică, cuplul din fișa de lucru nu e o recomandare: e o cerință de calitate care se verifică la audit. Scula trebuie să-l dea la fel la prima și la a mia îmbinare, iar operatorul trebuie să simtă clar când a ajuns la valoare.',
        steps: [
          { title: 'Alegi domeniul', text: 'Cheia lucrează cel mai precis în mijlocul scalei — valoarea de pe stație să cadă între 20% și 80% din domeniu.' },
          { title: 'Reglezi și blochezi', text: 'Valoarea se setează o dată, se blochează și se marchează pe stație.' },
          { title: 'Verifici periodic', text: 'Control la intervale fixe și după orice cădere — cu jurnal pentru audit.' },
        ],
      },
      { kind: 'carousel', title: 'Chei dinamometrice', text: 'Pentru îmbinările la care cuplul se verifică, nu se ghicește.', subs: ['Chei dinamometrice'] },
      { kind: 'carousel', title: 'Antrenoare cu clichet', text: 'Pas fin pentru spații înguste, inclusiv variante cu acumulator.', subs: ['Antrenoare cu clichet', 'Chei cu clichet cu acumulator'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Chei tubulare și prelungitoare', text: 'Tubulare scurte, lungi și de impact, reducții și prelungitoare.', subs: ['Chei tubulare', 'Prelungitoare și reducții tubulare'] },
      { kind: 'carousel', title: 'Imbus și torx', text: 'Pentru șuruburile cu locaș interior din subansamble.', subs: ['Chei imbus', 'Chei torx'] },
      { kind: 'tip', text: 'La finalul turei, cheia dinamometrică cu arc se descarcă la valoarea minimă a scalei — arcul lăsat tensionat peste noapte pierde precizie în timp.', by: TEAM },
      { ...OFFER, title: 'Chei pentru fiecare stație', text: 'Trimite-ne valorile de cuplu și tipul îmbinărilor — propunem domeniile potrivite și variante de la mai mulți producători.' },
    ],
  },
  {
    slug: 'aer-comprimat-scule-pneumatice-linie-auto',
    type: 'ghid',
    parent: 'scule-industria-auto-linii-asamblare',
    profession: 'Aer comprimat',
    title: 'Aer comprimat la stație: scule pneumatice pentru linia auto',
    domain: 'Industria auto · pneumatică',
    headline: 'Ușoare, rezistente, fără baterii de schimbat.',
    excerpt: 'Unelte și polizoare pneumatice, pistoale, dălți, furtunuri și cuple — pentru stațiile legate la rețeaua de aer a halei.',
    metaTitle: 'Scule pneumatice pentru linii de asamblare auto | Zona Scule',
    metaDescription: 'Unelte cu aer comprimat, polizoare pneumatice, pistoale, dălți, compresoare, furtunuri și conectori pentru stațiile de lucru din industria auto.',
    sections: [
      {
        kind: 'intro',
        lead: 'Unde hala are rețea de aer, scula pneumatică rămâne cea mai ușoară și mai rezistentă variantă pentru ritmul de tură: fără acumulatori de încărcat, fără motoare care se încălzesc. Condiția e ca aerul să ajungă curat, uscat și la presiunea corectă.',
        steps: [
          { title: 'Presiune și debit', text: 'Scula cere un debit anume la 6,3 bar — furtunul și cuplele nu trebuie să-l strangileze.' },
          { title: 'Aer pregătit', text: 'Filtru, regulator și ungere la punctul de consum prelungesc viața sculei.' },
          { title: 'Ergonomie', text: 'Greutate mică, vibrații reduse și evacuare a aerului departe de mână.' },
        ],
      },
      { kind: 'carousel', title: 'Unelte cu aer comprimat', text: 'Pentru înșurubare, găurire și operații repetitive la stație.', subs: ['Unelte cu Aer Comprimat', 'Unelte Pneumatice', 'Pistoale Pneumatice'] },
      { kind: 'carousel', title: 'Polizoare pneumatice', text: 'Drepte și unghiulare, pentru debavurare și retuș.', subs: ['Polizoare Pneumatice'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Dălți și ciocane cu ace', text: 'Pentru curățare de sudură și desprinderi.', subs: ['Dălți Pneumatice', 'Ciocane cu Ace Pneumatice'] },
      { kind: 'carousel', title: 'Aer: compresoare, furtunuri, cuple', text: 'De la sursă până la sculă, fără pierderi.', subs: ['Compresoare de aer', 'Furtunuri & conectori', 'Furtunuri și tuburi', 'Accesorii Pneumatice'] },
      { kind: 'tip', text: 'Dacă o sculă pneumatică „pierde putere” spre capătul liniei, vinovatul e de obicei furtunul prea lung sau prea subțire, nu scula — căderea de presiune pe traseu se măsoară la cupla sculei.', by: TEAM },
      { ...OFFER, title: 'Echipăm stațiile pneumatice', text: 'Spune-ne presiunea rețelei și operațiile — revenim cu scule, cuple și furtunuri potrivite.' },
    ],
  },
  {
    slug: 'finisaj-si-retus-de-suprafata-industria-auto',
    type: 'ghid',
    parent: 'scule-industria-auto-linii-asamblare',
    profession: 'Finisaj și retuș',
    title: 'Finisaj și retuș de suprafață în industria auto',
    domain: 'Industria auto · finisaj',
    headline: 'Un defect de vopsea se scoate, nu se ascunde.',
    excerpt: 'Discuri cu velcro, foi și nețesute, mașini și consumabile de lustruit — pentru retușul de suprafață la finalul liniei.',
    metaTitle: 'Abrazive și lustruire pentru retuș în industria auto | Zona Scule',
    metaDescription: 'Discuri cu velcro, foi abrazive, abrazive nețesute, polizoare și mașini de lustruit, pâsle, burete și paste de lustruit pentru retușul de suprafață în industria auto.',
    sections: [
      {
        kind: 'intro',
        lead: 'La finalul liniei, retușul de suprafață trebuie să scoată incluziunea sau zgârietura fără să lase urmă: granulații în trepte, presiune mică, apoi lustruire până la luciul original.',
        steps: [
          { title: 'Șlefuire în trepte', text: 'Pornești cu granulația care scoate defectul, apoi urci treptat până dispar urmele.' },
          { title: 'Nivelare fină', text: 'Nețesutele și foile fine uniformizează zona fără să taie adânc.' },
          { title: 'Lustruire', text: 'Pâslă sau burete cu pasta potrivită readuc luciul.' },
        ],
      },
      { kind: 'carousel', title: 'Discuri cu velcro', text: 'Schimbare rapidă între granulații, pe mașini orbitale și polizoare.', subs: ['Discuri cu Velcro'] },
      { kind: 'carousel', title: 'Foi și abrazive nețesute', text: 'Pentru lucru manual și nivelare fină.', subs: ['Foi abrazive', 'Abrazive Nețesute', 'Bureți abrazivi & Blocuri de șlefuire'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Mașini de lustruit', text: 'Rotative și orbitale, cu turație reglabilă.', subs: ['Polizoare și mașini de lustruit', 'Maşini de lustruit'] },
      { kind: 'carousel', title: 'Consumabile de lustruire', text: 'Discuri, capace, role și paste — pentru fiecare treaptă.', subs: ['Discuri de lustruit', 'Capace de Lustruit', 'Role de Lustruit', 'Paste de Lustruit'] },
      { kind: 'tip', text: 'Nu sări mai mult de o treaptă de granulație: de la P800 direct la P2000 rămân zgârieturi pe care lustruirea doar le scoate în evidență.', by: TEAM },
      { ...OFFER, title: 'Consumabile de finisaj, pe stoc', text: 'Spune-ne ce granulații și ce mașini folosiți — pregătim stoc dedicat și livrări programate.' },
    ],
  },
  {
    slug: 'mentenanta-in-uzina-auto',
    type: 'ghid',
    parent: 'scule-industria-auto-linii-asamblare',
    profession: 'Mentenanță',
    title: 'Mentenanța în uzina auto: diagnoză, extracție, iluminat',
    domain: 'Industria auto · mentenanță',
    headline: 'O linie oprită costă mai mult decât orice sculă.',
    excerpt: 'Camere termice și de inspecție, extractoare, iluminat portabil și instrumente de măsură — pentru echipele care țin linia în mișcare.',
    metaTitle: 'Scule pentru mentenanță în industria auto | Zona Scule',
    metaDescription: 'Camere termice și termodetectoare, camere de inspecție, extractoare de rulmenți, lanterne și iluminat portabil, instrumente de măsură pentru mentenanța liniilor auto.',
    sections: [
      {
        kind: 'intro',
        lead: 'Echipa de mentenanță lucrează contra timpului: găsește cauza, scoate piesa, montează alta, repornește linia. Diagnoza bună scurtează căutarea, iar sculele de extracție și lumina bună scurtează reparația.',
        steps: [
          { title: 'Găsești cauza', text: 'Termografia arată un rulment sau un contact care se încălzește înainte să cedeze.' },
          { title: 'Vezi înăuntru', text: 'Camera de inspecție intră unde nu ajunge ochiul, fără demontare.' },
          { title: 'Repari curat', text: 'Extractoare pentru rulmenți și pinioane, lumină pe zona de lucru, măsură la montaj.' },
        ],
      },
      { kind: 'carousel', title: 'Termografie și diagnoză', text: 'Camere termice, termodetectoare și aparate de diagnoză.', subs: ['Camere termice şi termodetectoare', 'Termodetectoare', 'Diagnosticare și inspecție', 'Camere de inspecție'] },
      { kind: 'carousel', title: 'Extractoare', text: 'Pentru rulmenți, pinioane și bucșe.', subs: ['Extractoare rulmenți', 'Extractoare'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Iluminat portabil', text: 'Lanterne, frontale și proiectoare pentru lucru în mașinărie.', subs: ['Lanterne', 'Lanterne frontale', 'Produse de iluminat portabile'] },
      { kind: 'carousel', title: 'Măsură și control', text: 'Pentru verificare la montaj și după intervenție.', subs: ['Instrumente masura'] },
      { kind: 'tip', text: 'O rundă termografică lunară pe tablouri și motoare costă o oră; un contact slăbit găsit la timp economisește o oprire neplanificată.', by: TEAM },
      { ...OFFER, title: 'Trusa echipei de mentenanță', text: 'Spune-ne ce utilaje întrețineți — propunem trusa de diagnoză, extracție și iluminat potrivită.' },
    ],
  },
  {
    slug: 'curatenie-si-protectie-in-hala-auto',
    type: 'ghid',
    parent: 'scule-industria-auto-linii-asamblare',
    profession: 'Hala și operatorul',
    title: 'Hala curată, operator protejat',
    domain: 'Industria auto · curățenie și protecție',
    headline: 'Praful și așchiile nu au ce căuta pe o caroserie.',
    excerpt: 'Aspiratoare industriale și umed-uscat, extracția prafului la sculă, protecție pentru ochi, auz, mâini și picioare — pentru hale de producție auto.',
    metaTitle: 'Curățenie industrială și echipament de protecție în hale auto | Zona Scule',
    metaDescription: 'Aspiratoare industriale și umed-uscat, extractoare de praf, protecția ochilor și auzului, mănuși, încălțăminte și îmbrăcăminte de protecție pentru industria auto.',
    sections: [
      {
        kind: 'intro',
        lead: 'În producția auto, curățenia e parte din calitate: particulele ajung pe suprafețe vopsite, în îmbinări și în ochii operatorilor. Aspirarea la sursă și echipamentul de protecție potrivit țin linia curată și oamenii în siguranță.',
        steps: [
          { title: 'Aspiri la sursă', text: 'Extractor legat direct la sculă — praful nu mai ajunge în aer.' },
          { title: 'Cureți hala', text: 'Aspiratoare industriale și umed-uscat pentru pardoseli, lichide și șpan.' },
          { title: 'Protejezi operatorul', text: 'Ochi, auz, mâini și picioare — pe fiecare stație, conform evaluării de risc.' },
        ],
      },
      { kind: 'carousel', title: 'Aspiratoare industriale', text: 'Pentru hale, șpan, lichide și praf fin.', subs: ['Aspiratoare industriale', 'Aspiratoare umed-uscat (NT)'] },
      { kind: 'carousel', title: 'Extracția prafului la sculă', text: 'Extractoare și accesorii pentru scule electrice.', subs: ['Extractoare praf & aspiratoare', 'Atașamente extractoare praf & aspiratoare', 'Accesorii extractoare praf & aspiratoare'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Ochi și auz', text: 'Ochelari de protecție și antifoane.', subs: ['Protecția ochilor', 'Protecție auditivă'] },
      { kind: 'carousel', title: 'Mâini, picioare, îmbrăcăminte', text: 'Mănuși, încălțăminte și îmbrăcăminte de lucru de siguranță.', subs: ['Mănuși de protecție', 'Încălțăminte de protecție', 'Îmbrăcăminte pentru lucru de siguranță'] },
      { kind: 'tip', text: 'Pentru praf fin de la șlefuire alege un aspirator cu clasă de praf M sau H — clasa L e pentru praf obișnuit și lasă particulele fine să treacă.', by: TEAM },
      { ...OFFER, title: 'Echipament pentru toată hala', text: 'Trimite-ne numărul de stații și evaluarea de risc — revenim cu aspiratoare, extracție și EIP pe mărimi.' },
    ],
  },
  {
    slug: 'scule-furnizori-industria-auto',
    type: 'meserie',
    profession: 'Furnizori auto',
    domain: 'Prelucrări pentru industria auto',
    headline: 'Debavurare, filetare și finisaj la toleranțe de serie.',
    excerpt: 'Pentru furnizorii de componente ai industriei auto: freze din carbură, scule de debavurare, tarozi, burghie, abrazive de rectificare și măsură.',
    metaTitle: 'Scule pentru furnizori auto — debavurare, tarozi, freze carbură | Zona Scule',
    metaDescription: 'Scule și abrazive pentru furnizorii industriei auto: freze din carbură, debavurare și teșire, tarozi și inserții filetate, burghie, discuri și pietre de rectificare, pile și instrumente de măsură.',
    sections: [
      {
        kind: 'intro',
        lead: 'Furnizorii de componente trăiesc din repetabilitate: aceeași bavură scoasă la fel pe mii de piese, același filet care intră la fel la client. Sculele de prelucrare și abrazivele potrivite scurtează ciclul și scad rebuturile.',
        steps: [
          { title: 'Debavurare și teșire', text: 'Freze din carbură, teșitoare și unelte de debavurare pentru muchii curate după frezare și găurire.' },
          { title: 'Găurire și filetare', text: 'Burghie elicoidale, tarozi, filiere și inserții filetate pentru filete de serie și reparații.' },
          { title: 'Rectificare și control', text: 'Discuri și pietre de rectificat, pile de precizie și instrumente de măsură.' },
        ],
      },
      { kind: 'carousel', title: 'Freze din carbură', text: 'Forme și danturi pentru oțel, inox, fontă și aluminiu.', subs: ['Freze din Carbură'] },
      { kind: 'carousel', title: 'Debavurare și teșire', text: 'Teșitoare și unelte de debavurare pentru muchii și găuri.', subs: ['Teșitoare', 'Unelte de Debavurare'] },
      { kind: 'carousel', title: 'Tarozi, filiere și inserții filetate', text: 'Filete de serie și reparații de filet fără piesă rebutată.', subs: ['Tarozi și filiere', 'Tarozi', 'Inserții Filetate'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Burghie pentru metal', text: 'HSS și HSS-Co pentru oțel și inox.', subs: ['Burghie Elicoidale', 'Burghie pentru metal'] },
      { kind: 'carousel', title: 'Rectificare', text: 'Discuri, pietre montate și CBN pentru rectificare și ascuțire.', subs: ['Discuri de Rectificat', 'Pietre Montate', 'Discuri de Rectificat CBN', 'Pietre de Rectificat'] },
      { kind: 'carousel', title: 'Perii industriale', text: 'Debavurare fină și curățare de suprafață, pe mașină sau manual.', subs: ['Perii Industriale'] },
      { kind: 'carousel', title: 'Pile de precizie și măsură', text: 'Pile ac și cu diamant pentru ajustaj, instrumente pentru control.', subs: ['Pile Ac', 'Pile diamantate', 'Instrumente masura'] },
      { kind: 'tip', text: 'La freze din carbură, dantura decide: tăietură în cruce pentru oțel și inox (așchii mici, control bun), dantură grosieră pentru aluminiu și materiale moi, ca să nu se încarce.', by: TEAM },
      { ...OFFER, title: 'Consumabile de producție, pe stoc', text: 'Spune-ne ce folosești azi — cod, cantitate lunară — și propunem stoc dedicat, echivalente și livrări programate.' },
    ],
  },
  {
    slug: 'scule-pentru-service-auto',
    type: 'meserie',
    profession: 'Mecanici auto',
    domain: 'Service auto',
    headline: 'Mai puțin timp pe elevator, mai multe mașini pe zi.',
    excerpt: 'Chei tubulare și antrenoare, dinamometrice, extractoare, scule pneumatice, iluminat și organizarea atelierului — pentru service-uri auto și mecanici.',
    metaTitle: 'Scule pentru service auto — chei, dinamometrice, pneumatice | Zona Scule',
    metaDescription: 'Scule profesionale pentru mecanici și service auto: chei tubulare, antrenoare, chei dinamometrice, extractoare, scule pneumatice, iluminat de atelier, curățenie și depozitare.',
    sections: [
      {
        kind: 'intro',
        lead: 'Într-un service, timpul pe elevator e bani. Cheia care intră din prima, lampa care luminează exact unde lucrezi și dulapul în care găsești scula fără să cauți fac diferența între trei și cinci mașini pe zi.',
        steps: [
          { title: 'Demontare', text: 'Tubulare de impact, antrenoare cu pas fin și extractoare pentru piese gripate.' },
          { title: 'Montaj la cuplu', text: 'Chei dinamometrice pentru roți, chiulase și suspensii — la valoarea din manual.' },
          { title: 'Atelier curat și organizat', text: 'Iluminat, depozitare și curățenie — pentru un atelier în care clientul are încredere.' },
        ],
      },
      { kind: 'carousel', title: 'Chei tubulare și antrenoare', text: 'Seturi de tubulare, antrenoare cu clichet și prelungitoare.', subs: ['Chei tubulare', 'Antrenoare cu clichet'] },
      { kind: 'carousel', title: 'Chei combinate și inelare', text: 'Pentru acces în spații înguste, unde clichetul nu încape.', subs: ['Chei combinate', 'Chei fixe și inelare'] },
      { kind: 'carousel', title: 'Chei dinamometrice și extractoare', text: 'Cuplu corect la montaj, piese scoase fără să le distrugi.', subs: ['Chei dinamometrice', 'Extractoare'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Chei imbus, torx și biți', text: 'Profilele din mașinile moderne, în variante scurte, lungi și de impact.', subs: ['Chei imbus', 'Chei torx', 'Biți și adaptoare'] },
      { kind: 'carousel', title: 'Scule pneumatice', text: 'Pentru atelierele cu compresor: polizoare și unelte cu aer comprimat.', subs: ['Unelte cu Aer Comprimat', 'Polizoare Pneumatice'] },
      { kind: 'carousel', title: 'Iluminat și acumulatori', text: 'Lămpi de lucru portabile și energie pentru sculele cu acumulator.', subs: ['Produse de iluminat portabile', 'Baterii & încărcătoare', 'Acumulatori'] },
      {
        kind: 'checklist',
        title: 'Dotarea minimă a unui post de lucru',
        items: [
          { name: 'Set tubulare 1/2″ și 1/4″', why: 'Acoperă aproape toate prinderile de pe o mașină.', q: 'set tubulare' },
          { name: 'Cheie dinamometrică 40–200 Nm', why: 'Roți, etriere, suspensii.', q: 'cheie dinamometrica' },
          { name: 'Set chei combinate', why: 'Acolo unde clichetul nu încape.', q: 'chei combinate' },
          { name: 'Set torx și imbus', why: 'Profile obligatorii pe mașinile noi.', q: 'chei torx' },
          { name: 'Lampă de lucru LED', why: 'Lumină unde lucrezi, nu unde e becul.', q: 'lampa' },
          { name: 'Dulap sau cărucior de scule', why: 'Fiecare sculă la locul ei, la îndemână.', q: 'carucior scule' },
        ],
      },
      { kind: 'carousel', title: 'Organizare și curățenie', text: 'Dulapuri metalice, sisteme modulare și aspiratoare umed-uscat pentru atelier.', subs: ['TOOLGUARD™ Sistem de depozitare metalic', 'PACKOUT™', 'Aspiratoare umed-uscat (NT)'] },
      {
        kind: 'faq',
        items: [
          { q: 'Tubulare cu 6 sau 12 laturi?', a: 'Cu 6 laturi pentru piulițe strânse sau ruginite — prind pe fețe, nu pe colțuri, și nu rotunjesc. Cu 12 laturi doar unde unghiul de lucru e foarte mic.' },
          { q: 'Pot folosi tubulare obișnuite pe pistolul de impact?', a: 'Nu. Tubularele de impact (negre, cu perete gros) sunt făcute să absoarbă șocurile; cele cromate obișnuite pot crăpa.' },
        ],
      },
    ],
  },
  {
    slug: 'scule-pentru-firme-de-constructii',
    type: 'meserie',
    profession: 'Firme de construcții',
    domain: 'Dotarea echipelor de șantier',
    headline: 'Echipe dotate la fel, pe o singură platformă.',
    excerpt: 'Pentru firmele care echipează mai multe echipe: platforme de acumulatori comune, aspirarea prafului, măsură, tăiere cu diamant, protecție și depozitare mobilă.',
    metaTitle: 'Dotarea firmelor de construcții — acumulatori, aspirare praf, EIP | Zona Scule',
    metaDescription: 'Scule și echipamente pentru firme de construcții: platforme de acumulatori 18V, aspiratoare pentru praf de beton, nivele laser, carote și discuri diamantate, echipament de protecție și depozitare.',
    sections: [
      {
        kind: 'intro',
        lead: 'Când dotezi mai multe echipe, contează mai puțin scula individuală și mai mult sistemul: aceeași platformă de acumulatori pe tot șantierul, aspirare conformă pentru praful de beton, echipamente de protecție pentru toată lumea și cutii care pleacă dimineața și se întorc seara complete.',
        steps: [
          { title: 'O singură platformă', text: 'Aceiași acumulatori în toate sculele — mai puține încărcătoare, mai puțin timp pierdut.' },
          { title: 'Praf sub control', text: 'Praful de beton conține silice: aspiratoare de clasă M și atașamente de aspirare direct la sculă.' },
          { title: 'Echipe complete', text: 'Protecție, măsură și depozitare mobilă, pentru fiecare echipă.' },
        ],
      },
      { kind: 'carousel', title: 'Platforme de acumulatori', text: 'Scule, seturi combinate, acumulatori și încărcătoare pe 18 V.', subs: ['Sistemul de 18 V', 'Seturi combinate', 'Baterii & încărcătoare'] },
      { kind: 'carousel', title: 'Aspirarea prafului', text: 'Extractoare și aspiratoare pentru praf de beton, plus atașamente direct la sculă.', subs: ['Extractoare praf & aspiratoare', 'Atașamente extractoare praf & aspiratoare', 'Aspiratoare industriale'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Măsură și trasare', text: 'Nivele laser, detectoare și instrumente de măsură.', subs: ['Nivele laser', 'Nivele laser cu linii în cruce', 'Instrumente masura', 'Detectoare'] },
      { kind: 'carousel', title: 'Carote și discuri diamantate', text: 'Treceri prin beton și zidărie, tăieri de rosturi.', subs: ['Carote diamantate pentru zidărie', 'Discuri de tăiere diamantate'] },
      { kind: 'carousel', title: 'Echipament de protecție', text: 'Căști, ochelari, antifoane și încălțăminte pentru toată echipa.', subs: ['Protecția capului', 'Protecția ochilor', 'Protecție auditivă', 'Încălțăminte'] },
      { kind: 'carousel', title: 'Depozitare mobilă', text: 'Sisteme modulare de cutii și inserții — trusa echipei, completă.', subs: ['PACKOUT™', 'Inserţii L-BOXX', 'Cutii de transport'] },
      { kind: 'tip', text: 'Alege platforma de acumulatori înainte de scule. Un acumulator comun pentru rotopercutor, polizor, înșurubător și lampă înseamnă că o echipă lucrează cu trei acumulatori în loc de zece.', by: TEAM },
      { kind: 'carousel', title: 'Schele și scări', text: 'Acces sigur la înălțime.', subs: ['Schele si scari'] },
      { ...OFFER, title: 'Dotăm echipe întregi', text: 'Spune-ne câte echipe și ce lucrări fac — propunem o dotare standard pe echipă, pe o singură platformă, cu preț pe volum.' },
    ],
  },
  {
    slug: 'dotari-institutii-seap',
    type: 'meserie',
    profession: 'Instituții publice',
    domain: 'Dotări prin S.E.A.P.',
    headline: 'Dotări pentru școli, primării și spitale, prin S.E.A.P.',
    excerpt: 'Ateliere școlare, întreținerea clădirilor, spații verzi și curățenie — scule și echipamente pentru instituții, achiziționate prin Sistemul Electronic de Achiziții Publice.',
    metaTitle: 'Dotări pentru instituții prin S.E.A.P. — scule și echipamente | Zona Scule',
    metaDescription: 'Scule și echipamente pentru instituții publice prin S.E.A.P.: dotarea atelierelor școlare, întreținerea clădirilor, spații verzi și curățenie. Ofertă conform specificațiilor tehnice.',
    sections: [
      {
        kind: 'intro',
        lead: 'Zona Scule este furnizor înregistrat în S.E.A.P. Pentru instituții, asta înseamnă o ofertă făcută după specificațiile tehnice din caietul de sarcini, documente complete și livrare cu garanție — de la o trusă pentru atelierul școlii la echipamentele de curățenie ale unui spital.',
        steps: [
          { title: 'Specificații', text: 'Ne trimiteți lista sau caietul de sarcini; propunem produse conforme și, unde e cazul, echivalente.' },
          { title: 'Ofertă și publicare', text: 'Pregătim oferta și, după caz, publicăm produsele în catalogul electronic S.E.A.P.' },
          { title: 'Livrare și garanție', text: 'Livrăm cu documentele necesare recepției și asigurăm service și piese.' },
        ],
      },
      { kind: 'carousel', title: 'Ateliere școlare', text: 'Menghine, truse și seturi de scule pentru atelierele liceelor tehnologice.', subs: ['Menghine', 'Seturi și truse de scule', 'Chei combinate'] },
      { kind: 'carousel', title: 'Scule electrice profesionale', text: 'Pentru echipele de întreținere și atelierele de practică.', subs: ['Scule Electrice Profesionale (BE)', 'Sistemul de 18 V'] },
      { kind: 'image' },
      { kind: 'carousel', title: 'Spații verzi', text: 'Aparate de grădină și accesorii pentru parcuri, curți și terenuri.', subs: ['Aparate electrice de grădină', 'Tundere și curățare', 'Atașamente echipamente pentru pădure și grădină'] },
      { kind: 'carousel', title: 'Curățenie în clădiri publice', text: 'Aspiratoare, mașini de spălat pardoseli și aparate cu presiune.', subs: ['Aspiratoare umed-uscat (NT)', 'Mașini de spălat-uscat', 'Apă rece'] },
      { kind: 'carousel', title: 'Protecția muncii', text: 'Ochelari, antifoane și mănuși pentru personalul tehnic.', subs: ['Protecția ochilor', 'Protecție auditivă', 'Mănuși de protecție'] },
      { kind: 'tip', text: 'Descrieți în caietul de sarcini performanța de care aveți nevoie (putere, capacitate, clasă de filtrare), nu un model anume — primiți mai multe oferte comparabile și un preț mai bun.', by: TEAM },
      { ...OFFER, title: 'Trimiteți-ne specificațiile', text: 'Ofertăm conform caietului de sarcini, cu documentele necesare. Răspundem de obicei în aceeași zi lucrătoare.', label: 'Solicită ofertă S.E.A.P.' },
      {
        kind: 'faq',
        items: [
          { q: 'Sunteți furnizor înregistrat în S.E.A.P.?', a: 'Da — Zona Scule (Technology Production SRL) este furnizor înregistrat pentru achiziții publice prin S.E.A.P.' },
          { q: 'Puteți oferta produse echivalente?', a: 'Da. Unde caietul de sarcini permite, propunem echivalente cu aceleași performanțe tehnice, de la alți producători pe care îi distribuim.' },
        ],
      },
    ],
  },

  // ══ Cum alegi… ════════════════════════════════════════════════════════════
  {
    slug: 'cum-alegi-discul-de-polizor',
    type: 'ghid',
    profession: 'Discul de polizor',
    title: 'Cum alegi discul de polizor potrivit',
    domain: 'Ghid · Abrazive',
    headline: 'Tăiere, degroșare sau lamelar — și de ce contează „INOX” pe etichetă.',
    excerpt: 'Tipurile de discuri pentru polizorul unghiular, pe ce material merge fiecare, diametre și turații maxime, și diferența dintre discurile pentru oțel și cele pentru inox.',
    metaTitle: 'Cum alegi discul de polizor: tăiere, degroșare, lamelar, inox | Zona Scule',
    metaDescription: 'Ghid pentru alegerea discului de polizor unghiular: discuri de tăiere, degroșare, lamelare, din fibră și diamantate; oțel vs inox; diametre și turații maxime.',
    sections: [
      {
        kind: 'intro',
        lead: 'Discul face mai mult decât polizorul: același aparat taie, degroșează sau finisează în funcție de ce montezi pe el. Un disc greșit se uzează în câteva minute, încinge piesa — sau, în cel mai rău caz, se sparge.',
        steps: [
          { title: 'Ce vrei să faci', text: 'Tăiere, degroșare, finisare sau curățare — fiecare are discul ei.' },
          { title: 'Pe ce material', text: 'Oțel, inox, aluminiu, beton sau piatră.' },
          { title: 'Pe ce polizor', text: 'Diametrul și turația maximă a discului trebuie să se potrivească cu polizorul.' },
        ],
      },
      {
        kind: 'compare',
        title: 'Tipuri de discuri',
        head: ['Disc', 'Grosime / construcție', 'Folosește-l pentru', 'Nu-l folosi pentru'],
        rows: [
          ['De tăiere', '0,8–3 mm, drept sau cu centru adâncit', 'Profile, țevi, bare, tablă', 'Șlefuire laterală — nu e făcut pentru presiune pe fețe'],
          ['De degroșare', '6–8 mm, cu centru adâncit', 'Îndepărtat material, cordoane de sudură', 'Finisaj — lasă zgârieturi adânci'],
          ['Lamelar', 'Lamele abrazive suprapuse, drept sau conic', 'Degroșare și finisaj în aceeași trecere', 'Tăiere'],
          ['Din fibră', 'Disc subțire pe taler-suport', 'Rugină, vopsea, suduri pe suprafețe mari', 'Tăiere, muchii ascuțite'],
          ['Diamantat', 'Segmentat, turbo sau continuu', 'Beton, zidărie, piatră, gresie', 'Metal'],
        ],
      },
      { kind: 'carousel', title: 'Discuri de tăiere', text: 'Subțiri pentru tăieri rapide și curate, cu pierdere minimă de material.', subs: ['Discuri de tăiere'] },
      { kind: 'carousel', title: 'Discuri lamelare', text: 'Granulații de la 40 (degroșare) la 120 (finisaj).', subs: ['Discuri Lamelare', 'Discuri evantai'] },
      {
        kind: 'rules',
        title: 'Reguli rapide',
        items: [
          { when: 'Lucrezi pe inox', then: 'Alege discuri marcate INOX — fără fier, sulf și clor, care ar face suprafața să ruginească ulterior.' },
          { when: 'Tai mult și repede', then: 'Disc de tăiere de 1 mm: taie mai repede, încinge mai puțin piesa.' },
          { when: 'Sudura trebuie să rămână vizibilă și curată', then: 'Disc lamelar în loc de degroșare: scoate materialul și finisează dintr-o dată.' },
          { when: 'Treci de la oțel la inox', then: 'Schimbă și discul, și peria — particulele de oțel rămase pe disc contaminează inoxul.' },
        ],
      },
      { kind: 'carousel', title: 'Discuri de degroșare și din fibră', text: 'Pentru îndepărtat rapid material și curățat suprafețe.', subs: ['Discuri de degroșare', 'Discuri din Fibră'] },
      {
        kind: 'compare',
        title: 'Diametru și turație maximă',
        text: 'Pentru discurile uzuale, cu viteza maximă de lucru de 80 m/s. Turația maximă e tipărită pe fiecare disc — trebuie să fie cel puțin cât turația polizorului.',
        head: ['Diametru', 'Turație maximă', 'Polizor tipic'],
        rows: [
          ['115 mm', '13 300 rot/min', 'Polizor mic, lucru fin'],
          ['125 mm', '12 200 rot/min', 'Cel mai folosit — atelier și șantier'],
          ['150 mm', '10 200 rot/min', 'Suprafețe mai mari'],
          ['180 mm', '8 500 rot/min', 'Polizor mare'],
          ['230 mm', '6 600 rot/min', 'Polizor mare — tăieri adânci, beton'],
        ],
      },
      { kind: 'carousel', title: 'Discuri diamantate', text: 'Pentru beton, zidărie, piatră și gresie.', subs: ['Discuri de tăiere diamantate'] },
      { kind: 'carousel', title: 'Polizoare unghiulare', text: 'Cu fir și cu acumulator, de la 115 la 230 mm.', subs: ['Polizoare unghiulare mici', 'Polizoare și mașini de lustruit'] },
      {
        kind: 'faq',
        items: [
          { q: 'Pot folosi un disc de tăiere pentru șlefuit?', a: 'Nu. Discurile de tăiere sunt subțiri și nu suportă presiune laterală — se pot sparge. Pentru șlefuit folosește discuri de degroșare sau lamelare.' },
          { q: 'Ce înseamnă discul „INOX”?', a: 'Discul conține sub 0,1% fier, sulf și clor. Altfel, particulele rămase pe suprafața inoxului ruginesc și îi strică protecția anticorozivă.' },
          { q: 'Ce granulație de disc lamelar aleg?', a: '40 pentru degroșare agresivă, 60–80 pentru uz general, 120 pentru finisaj înainte de vopsire sau lustruire.' },
        ],
      },
    ],
  },
  {
    slug: 'ce-burghiu-pentru-ce-material-sds-plus-sds-max',
    type: 'ghid',
    profession: 'Burghiul potrivit',
    title: 'Ce burghiu pentru ce material',
    domain: 'Ghid · Găurire',
    headline: 'Beton, metal, lemn sau gresie — și când ai nevoie de SDS-max în loc de SDS-plus.',
    excerpt: 'Burghiul potrivit pentru fiecare material, cu sau fără percuție, și diferențele dintre prinderile SDS-plus și SDS-max.',
    metaTitle: 'Ce burghiu pentru ce material? SDS-plus vs SDS-max | Zona Scule',
    metaDescription: 'Ghid de alegere a burghielor: pentru beton și zidărie, metal și inox, lemn, gresie și faianță. Diferențele dintre SDS-plus și SDS-max, cu sau fără percuție.',
    sections: [
      {
        kind: 'intro',
        lead: 'Un burghiu greșit nu doar găurește încet — se tocește, arde materialul sau crapă placa. Vârful, materialul burghiului și modul de lucru al mașinii trebuie alese împreună.',
        steps: [
          { title: 'Materialul', text: 'Decide forma vârfului și din ce e făcut burghiul.' },
          { title: 'Mașina', text: 'Cu percuție pentru zidărie, fără percuție pentru metal, lemn și ceramică.' },
          { title: 'Prinderea', text: 'Mandrină, SDS-plus sau SDS-max — trebuie să se potrivească cu mașina.' },
        ],
      },
      {
        kind: 'compare',
        title: 'Material → burghiu',
        head: ['Material', 'Burghiu', 'Mod de lucru'],
        rows: [
          ['Beton, beton armat', 'SDS-plus / SDS-max cu vârf din carbură, 2 sau 4 tăișuri', 'Ciocan rotopercutor'],
          ['Cărămidă, piatră', 'Burghiu pentru zidărie cu vârf din carbură', 'Percuție'],
          ['BCA', 'Burghiu pentru zidărie', 'Fără percuție — materialul se sfărâmă'],
          ['Oțel', 'HSS-G (șlefuit)', 'Fără percuție, turație moderată, ulei de găurit'],
          ['Inox', 'HSS-Co 5% sau 8% (cobalt)', 'Turație mică, presiune constantă, răcire'],
          ['Lemn', 'Cu vârf de centrare, spirală sau Forstner', 'Turație mare, fără percuție'],
          ['Gresie, faianță', 'Diamantat sau cu vârf de carbură în lance', 'Fără percuție, răcire'],
        ],
      },
      { kind: 'carousel', title: 'Burghie SDS pentru beton și zidărie', text: 'Pentru ciocane rotopercutoare.', subs: ['Burghie pentru zidărie și beton', 'Burghie pentru beton', 'Burghie pentru zidărie'] },
      { kind: 'carousel', title: 'Burghie pentru metal', text: 'HSS, HSS-Co și în trepte.', subs: ['Burghie pentru metal', 'Burghie Elicoidale', 'Seturi de burghie pentru metal'] },
      {
        kind: 'compare',
        title: 'SDS-plus vs SDS-max',
        head: ['', 'SDS-plus', 'SDS-max'],
        rows: [
          ['Coada', 'Ø 10 mm', 'Ø 18 mm'],
          ['Ciocane tipice', '2–4 kg', 'peste 5 kg'],
          ['Găuri în beton', 'aprox. 4–30 mm', 'aprox. 12–50 mm și carote mari'],
          ['Folosit pentru', 'Găurire zilnică, dibluri, șlițuri ușoare', 'Găuri mari, carote, spargere și demolare'],
          ['Compatibilitate', 'Doar mașini SDS-plus', 'Doar mașini SDS-max'],
        ],
        note: 'Prinderile nu sunt interschimbabile. Există adaptoare SDS-plus → mandrină pentru burghie cu coadă cilindrică, dar nu pentru lucru cu percuție.',
      },
      { kind: 'carousel', title: 'Burghie pentru lemn', text: 'Cu vârf de centrare, lungi și Forstner.', subs: ['Burghie pentru lemn'] },
      { kind: 'carousel', title: 'Burghie pentru gresie și faianță', text: 'Diamantate și pentru plăci ceramice.', subs: ['Burghie pentru plăci ceramice', 'Burghie diamantate'] },
      { kind: 'carousel', title: 'Burghie universale', text: 'Multi Material — pentru când nu știi ce e în perete.', subs: ['Burghie Multi Material', 'Burghie universale'] },
      { kind: 'tip', text: 'La beton armat, un burghiu cu 4 tăișuri nu se blochează când lovește armătura — cel cu 2 tăișuri se poate agăța și smulge mașina din mână.', by: TEAM },
      {
        kind: 'faq',
        items: [
          { q: 'Pot găuri beton cu o mașină fără percuție?', a: 'Practic nu — burghiul se încinge și abia înaintează. Pentru beton ai nevoie de percuție, ideal de un ciocan rotopercutor SDS-plus.' },
          { q: 'Ce e HSS-Co?', a: 'Oțel rapid aliat cu cobalt (5% sau 8%). Rezistă la temperaturi mai mari, deci ține mai mult pe inox și oțeluri dure.' },
        ],
      },
    ],
  },
  {
    slug: 'cati-dinti-panza-circulara',
    type: 'ghid',
    profession: 'Pânza circulară',
    title: 'Câți dinți trebuie să aibă pânza circulară',
    domain: 'Ghid · Tăiere lemn',
    headline: 'Puțini dinți pentru viteză, mulți pentru finețe — și forma lor pentru material.',
    excerpt: 'Numărul de dinți, forma dinților și unghiul de atac pentru lemn masiv, plăci melaminate, laminate și aluminiu.',
    metaTitle: 'Câți dinți la pânza circulară? Ghid pentru lemn, PAL, aluminiu | Zona Scule',
    metaDescription: 'Cum alegi pânza de ferăstrău circular: numărul de dinți pentru spintecare și tăieri fine, formele de dinți (alternanți, plați, trapez-plat) și pânzele pentru PAL, laminat și aluminiu.',
    sections: [
      {
        kind: 'intro',
        lead: 'Aceeași mașină taie repede și grosier sau încet și fin, în funcție de pânză. Numărul de dinți decide viteza și finețea; forma dinților decide pe ce material lucrezi fără ciupituri.',
        steps: [
          { title: 'Direcția tăieturii', text: 'Spintecare (în lungul fibrei) sau retezare (transversal).' },
          { title: 'Materialul', text: 'Lemn masiv, PAL melaminat, laminat, aluminiu.' },
          { title: 'Mașina', text: 'Diametrul și alezajul pânzei trebuie să se potrivească.' },
        ],
      },
      {
        kind: 'compare',
        title: 'Număr de dinți (pentru Ø 216–254 mm)',
        head: ['Dinți', 'Pentru', 'Rezultat'],
        rows: [
          ['24–32', 'Spintecare rapidă în lemn masiv', 'Rapid, tăietură grosieră'],
          ['40–48', 'Universal — spintecare și retezare', 'Echilibru între viteză și finețe'],
          ['60–80', 'Retezare fină, plăci, lemn tare', 'Tăietură curată, mai lentă'],
          ['80–96', 'PAL melaminat, laminat, aluminiu (cu dinți trapez-plat)', 'Muchii fără ciupituri'],
        ],
      },
      {
        kind: 'compare',
        title: 'Forma dinților',
        head: ['Formă', 'Cum arată', 'Pentru'],
        rows: [
          ['Alternanți (WZ / ATB)', 'Dinți teșiți alternativ stânga-dreapta', 'Lemn, retezare, tăieturi curate'],
          ['Plați (FZ / FT)', 'Dinți drepți', 'Spintecare rapidă în lemn masiv'],
          ['Trapez-plat (TF / TCG)', 'Alternativ trapez și plat', 'PAL melaminat, laminat, aluminiu, plastic'],
          ['Unghi de atac negativ', 'Dinți înclinați înapoi', 'Fierăstraie de retezat și glisante — nu trag piesa'],
        ],
      },
      { kind: 'carousel', title: 'Pânze de ferăstrău circular', text: 'Pentru mașini portabile, de masă și de retezat.', subs: ['Pânze de ferăstrău circular', 'Pânze de ferăstrău circular pentru lemn'] },
      {
        kind: 'rules',
        title: 'Reguli rapide',
        items: [
          { when: 'Muchia PAL-ului se ciupește', then: 'Treci la o pânză trapez-plat cu peste 60 de dinți și taie cu fața bună în sus pe fierăstrăul de masă (în jos pe cel portabil).' },
          { when: 'Lemnul se arde la tăiere', then: 'Pânza e tocită sau are prea mulți dinți pentru grosimea piesei — folosește mai puțini dinți la spintecare.' },
          { when: 'Tai aluminiu', then: 'Doar pânze dedicate, cu dinți trapez-plat și unghi negativ, la turația recomandată.' },
        ],
      },
      { kind: 'carousel', title: 'Mașini pentru lemn', text: 'Fierăstraie circulare, de retezat și alte scule pentru prelucrarea lemnului.', subs: ['Prelucrarea lemnului'] },
      { kind: 'tip', text: 'Verifică întotdeauna alezajul (Ø 30 mm e cel mai des întâlnit) și turația maximă înscrisă pe pânză înainte de montaj.', by: TEAM },
      {
        kind: 'faq',
        items: [
          { q: 'Mai mulți dinți înseamnă o pânză mai bună?', a: 'Nu neapărat — înseamnă o tăietură mai fină, dar mai lentă. Pentru spintecare în lemn gros, mulți dinți încarcă și ard lemnul.' },
          { q: 'Pot tăia laminat cu pânza pentru lemn?', a: 'Se poate, dar muchia se va ciupi. Pentru laminat și PAL melaminat alege o pânză cu dinți trapez-plat.' },
        ],
      },
    ],
  },
  {
    slug: 'aspirator-industrial-clase-filtrare-l-m-h',
    type: 'ghid',
    profession: 'Aspiratorul industrial',
    title: 'Aspiratorul industrial: clasele de filtrare L, M și H',
    domain: 'Ghid · Aspirare',
    headline: 'Ce praf aspiri decide ce clasă îți trebuie.',
    excerpt: 'Ce înseamnă clasele de praf L, M și H, ce aspirator trebuie pentru praful de beton, lemn sau azbest, și ce mai contează: debit, depresiune, curățarea filtrului.',
    metaTitle: 'Aspirator industrial: clase de filtrare L, M, H explicate | Zona Scule',
    metaDescription: 'Cum alegi un aspirator industrial după clasa de praf L, M sau H: ce praf reține fiecare, praful de beton (silice), lemn și azbest, plus debit, depresiune și curățarea filtrului.',
    sections: [
      {
        kind: 'intro',
        lead: 'Praful fin de pe șantier nu se vede, dar se respiră. Clasele de praf L, M și H arată cât de bine reține aspiratorul particulele — și sunt alese după cât de periculos e praful, nu după cât de mult e.',
        steps: [
          { title: 'Ce praf', text: 'Gips, lemn moale, beton, lemn de esență tare, azbest.' },
          { title: 'Ce clasă', text: 'L, M sau H, după cât de periculos este praful.' },
          { title: 'Cum lucrezi', text: 'Debit pentru aspirare la sculă, curățare automată a filtrului pentru lucru continuu.' },
        ],
      },
      {
        kind: 'compare',
        title: 'Clasele de praf',
        head: ['Clasă', 'Trece prin filtru', 'Pentru praf', 'Exemple'],
        rows: [
          ['L', 'sub 1%', 'Cu risc scăzut', 'Praf menajer, gips, lemn moale'],
          ['M', 'sub 0,1%', 'Cu risc mediu', 'Beton, mortar, gresie (silice), lemn de esență tare, vopsele'],
          ['H', 'sub 0,005%', 'Cu risc ridicat, cancerigen sau patogen', 'Azbest, mucegai, fibre minerale, plumb'],
        ],
        note: 'Aspiratoarele de clasă M și H au și alarmă de debit: te avertizează când filtrul se colmatează și aspirarea scade sub nivelul sigur.',
      },
      { kind: 'carousel', title: 'Aspiratoare umed-uscat', text: 'Pentru praf, murdărie grosieră și lichide.', subs: ['Aspiratoare umed-uscat (NT)'] },
      { kind: 'carousel', title: 'Aspiratoare industriale', text: 'Pentru lucru continuu și volume mari.', subs: ['Aspiratoare industriale'] },
      {
        kind: 'rules',
        title: 'Reguli rapide',
        items: [
          { when: 'Tai, găurești sau șlefuiești beton', then: 'Minimum clasa M — praful de beton conține silice cristalină.' },
          { when: 'Lucrezi cu stejar, fag sau MDF', then: 'Clasa M — praful de lemn de esență tare este cancerigen.' },
          { when: 'Există suspiciune de azbest', then: 'Doar clasa H și procedura dedicată — nu improviza.' },
          { when: 'Aspiri direct de la sculă', then: 'Alege un aspirator cu priză pentru sculă și pornire automată.' },
        ],
      },
      { kind: 'carousel', title: 'Extractoare de praf pentru șantier', text: 'Pentru aspirare la sculă — rotopercutoare, polizoare, șlefuitoare.', subs: ['Extractoare praf & aspiratoare', 'Aspiratoare uscate (T)'] },
      { kind: 'carousel', title: 'Accesorii și atașamente', text: 'Furtunuri, capete de aspirare și atașamente pentru scule.', subs: ['Accesorii extractoare praf & aspiratoare', 'Atașamente extractoare praf & aspiratoare'] },
      { kind: 'tip', text: 'La praful fin de beton, curățarea automată a filtrului contează cât clasa: fără ea, filtrul se colmatează în câteva minute și aspiratorul trage din ce în ce mai slab.', by: TEAM },
      {
        kind: 'faq',
        items: [
          { q: 'Pot aspira praf de beton cu un aspirator obișnuit?', a: 'Nu e recomandat — praful fin trece prin filtru și ajunge înapoi în aer, iar motorul se uzează. Folosește un aspirator de clasă M, cu curățare a filtrului.' },
          { q: 'Ce înseamnă „umed-uscat”?', a: 'Aspiratorul poate aspira și lichide, nu doar praf — util pe șantier, în ateliere și la curățenia după inundații.' },
        ],
      },
    ],
  },
  {
    slug: 'aparat-spalat-cu-presiune-bar-debit-apa-calda',
    type: 'ghid',
    profession: 'Aparatul cu presiune',
    title: 'Cum alegi aparatul de spălat cu presiune',
    domain: 'Ghid · Curățenie',
    headline: 'Presiunea desprinde murdăria, debitul o spală — iar apa caldă topește grăsimea.',
    excerpt: 'Ce înseamnă bar și l/h, când ai nevoie de apă caldă, și ce aparat se potrivește pentru uz ocazional, profesional sau industrial.',
    metaTitle: 'Aparat de spălat cu presiune: bar, debit l/h, apă caldă | Zona Scule',
    metaDescription: 'Cum alegi un aparat de spălat cu presiune: presiunea în bar, debitul în l/h, apă rece sau caldă, și ce clasă de aparat pentru uz ocazional, profesional sau industrial.',
    sections: [
      {
        kind: 'intro',
        lead: 'Cel mai des, aparatele se compară după presiune — dar la fel de mult contează debitul: presiunea desprinde murdăria, apa o duce. Pentru grăsimi și uleiuri, apa caldă face în câteva minute ce apa rece nu face deloc.',
        steps: [
          { title: 'Presiunea (bar)', text: 'Cât de puternic lovește jetul — desprinde murdăria lipită.' },
          { title: 'Debitul (l/h)', text: 'Câtă apă trece — viteza cu care cureți suprafața.' },
          { title: 'Temperatura', text: 'Apă rece pentru murdărie obișnuită, caldă pentru grăsimi și uleiuri.' },
        ],
      },
      {
        kind: 'compare',
        title: 'Ce aparat pentru ce utilizare',
        head: ['Utilizare', 'Presiune', 'Debit', 'Apă'],
        rows: [
          ['Ocazională', '100–130 bar', '350–450 l/h', 'Rece'],
          ['Profesională zilnică (auto, șantier, agricultură)', '140–170 bar', '500–700 l/h', 'Rece'],
          ['Industrie, grăsimi, uleiuri, alimentar', '150–200 bar', '700–1 000 l/h', 'Caldă, până la ~80 °C, sau abur'],
        ],
        note: 'Valori orientative. Aparatele profesionale au de obicei motoare lente, cu 4 poli (în jur de 1 450 rot/min) și pompe cu pistoane din ceramică — mai multe ore de funcționare.',
      },
      { kind: 'carousel', title: 'Aparate cu apă rece', text: 'Pentru majoritatea lucrărilor de curățenie.', subs: ['Apă rece'] },
      { kind: 'carousel', title: 'Aparate cu apă caldă și abur', text: 'Pentru grăsimi, uleiuri și igienizare.', subs: ['Apă caldă și abur'] },
      {
        kind: 'rules',
        title: 'Reguli rapide',
        items: [
          { when: 'Speli utilaje și vehicule murdare de ulei', then: 'Apă caldă — curăță de câteva ori mai repede și folosește mai puțin detergent.' },
          { when: 'Cureți suprafețe mari (curți, fațade)', then: 'Debit mare și o duză rotativă sau un curățitor de suprafețe.' },
          { when: 'Lucrezi pe suprafețe delicate', then: 'Presiune mai mică și duză plată — nu duza rotativă.' },
        ],
      },
      { kind: 'carousel', title: 'Accesorii și detergenți', text: 'Duze, lănci, furtunuri și detergenți potriviți fiecărei murdării.', subs: ['Accesorii pentru spălătorie de înaltă presiune', 'Detergenți industriali'] },
      { kind: 'tip', text: 'Aplică detergentul de jos în sus și clătește de sus în jos — așa nu rămân urme de scurgere pe suprafețele verticale.', by: TEAM },
      {
        kind: 'faq',
        items: [
          { q: 'E mai bună o presiune mai mare?', a: 'Nu întotdeauna. Peste un anumit nivel, presiunea poate deteriora suprafața; debitul e cel care scurtează timpul de spălare.' },
          { q: 'Când merită un aparat cu apă caldă?', a: 'Când speli des grăsimi, uleiuri sau murdărie organică — service-uri auto, ferme, industria alimentară, utilaje.' },
        ],
      },
    ],
  },
  {
    slug: 'nivela-laser-linie-verde-sau-rosie',
    type: 'ghid',
    profession: 'Nivela laser',
    title: 'Nivela laser: linie verde sau roșie?',
    domain: 'Ghid · Măsură și trasare',
    headline: 'Vizibilitate, rază de lucru și precizie — ce contează la o nivelă laser.',
    excerpt: 'Diferența dintre laserul verde și cel roșu, raza de lucru cu și fără receptor, tipuri de linii și ce precizie îți trebuie.',
    metaTitle: 'Nivela laser: verde sau roșie, rază de lucru, precizie | Zona Scule',
    metaDescription: 'Cum alegi o nivelă laser: linie verde vs roșie, raza de lucru cu și fără receptor, laser cu linii în cruce sau 360°, precizie și autonivelare.',
    sections: [
      {
        kind: 'intro',
        lead: 'Nivela laser înlocuiește furtunul cu apă și firul cu plumb — dacă o vezi. Culoarea fasciculului, tipul liniilor și raza de lucru decid unde e utilă: într-o baie, într-o hală sau în exterior.',
        steps: [
          { title: 'Culoarea', text: 'Verde pentru vizibilitate, roșu pentru autonomie și preț.' },
          { title: 'Liniile', text: 'Cruce pentru o cameră, 360° pentru toată încăperea dintr-o poziție.' },
          { title: 'Raza', text: 'Cât vezi cu ochiul liber și cât cu receptorul.' },
        ],
      },
      {
        kind: 'compare',
        title: 'Verde vs roșu',
        head: ['', 'Laser verde', 'Laser roșu'],
        rows: [
          ['Vizibilitate', 'De aproximativ 4 ori mai vizibil pentru ochi', 'Bun în interior, slab la lumină puternică'],
          ['Rază fără receptor (interior)', 'Mai mare', 'Mai mică'],
          ['Autonomie', 'Mai mică', 'Mai mare'],
          ['Preț', 'Mai mare', 'Mai mic'],
          ['În exterior', 'Cu receptor', 'Cu receptor'],
        ],
        note: 'În exterior, în plin soare, ambele au nevoie de receptor — acolo raza reală e dată de receptor, nu de culoare.',
      },
      { kind: 'carousel', title: 'Nivele laser cu linii în cruce', text: 'Pentru faianță, mobilier, prize și tavane.', subs: ['Nivele laser cu linii în cruce'] },
      { kind: 'carousel', title: 'Nivele laser', text: 'Cu linii, puncte și 360°.', subs: ['Nivele laser'] },
      {
        kind: 'rules',
        title: 'Reguli rapide',
        items: [
          { when: 'Lucrezi în încăperi luminoase sau mari', then: 'Laser verde.' },
          { when: 'Montezi faianță sau mobilier într-o cameră', then: 'Laser cu linii în cruce, roșu sau verde.' },
          { when: 'Faci tavane false sau pereți de gips-carton', then: 'Laser cu linii de 360° — trasezi toată încăperea dintr-o singură poziție.' },
          { when: 'Lucrezi afară', then: 'Alege un model care acceptă receptor.' },
        ],
      },
      { kind: 'carousel', title: 'Nivele cu bulă și instrumente de măsură', text: 'Pentru verificări rapide și cote.', subs: ['Nivele', 'Instrumente masura'] },
      { kind: 'tip', text: 'Verifică periodic precizia: marchează linia pe un perete, rotește nivela la 180° și marchează din nou. Diferența dintre semne îți arată dacă nivela trebuie recalibrată.', by: TEAM },
      {
        kind: 'faq',
        items: [
          { q: 'Ce precizie trebuie să aibă o nivelă laser?', a: 'Pentru construcții și finisaje, o precizie de aproximativ ±0,3 mm/m este suficientă — înseamnă ±3 mm la 10 m.' },
          { q: 'Ce înseamnă autonivelare?', a: 'Nivela își corectează singură poziția în intervalul de autonivelare (de obicei câteva grade) și avertizează când e prea înclinată.' },
        ],
      },
    ],
  },
  {
    slug: 'platforme-acumulatori-12v-18v-ampshare-m18',
    type: 'ghid',
    profession: 'Platforma de acumulatori',
    title: 'Platforme de acumulatori: 12 V vs 18 V, AMPShare vs M18',
    domain: 'Ghid · Scule cu acumulator',
    headline: 'Alegi o dată platforma — apoi toate sculele vin pe același acumulator.',
    excerpt: 'Când ajung 12 V și când îți trebuie 18 V, ce înseamnă o platformă de acumulatori și cum se compară Bosch AMPShare și Milwaukee M18.',
    metaTitle: 'Platforme de acumulatori: 12V vs 18V, AMPShare vs M18 | Zona Scule',
    metaDescription: 'Cum alegi platforma de scule cu acumulator: 12 V vs 18 V, capacitate (Ah), motoare fără perii, și comparația dintre Bosch Professional 18V AMPShare și Milwaukee M18.',
    sections: [
      {
        kind: 'intro',
        lead: 'Când cumperi prima sculă cu acumulator, de fapt alegi o platformă: acumulatorii și încărcătoarele se potrivesc doar în sculele din același sistem. Merită ales după ce vei folosi peste doi ani, nu după o singură sculă.',
        steps: [
          { title: 'Tensiunea', text: '12 V pentru scule compacte, 18 V pentru putere.' },
          { title: 'Capacitatea', text: 'Ah decide cât ține acumulatorul, nu cât de puternică e scula.' },
          { title: 'Ecosistemul', text: 'Câte scule există pe platformă — și de la ce producători.' },
        ],
      },
      {
        kind: 'compare',
        title: '12 V vs 18 V',
        head: ['', '12 V', '18 V'],
        rows: [
          ['Greutate', 'Mică — lucru deasupra capului, spații înguste', 'Mai mare'],
          ['Putere', 'Suficientă pentru înșurubare și găuri mici', 'Pentru găurire în beton, polizare, tăiere'],
          ['Potrivit pentru', 'Instalatori, electricieni, montaj mobilier', 'Șantier, construcții, prelucrări grele'],
          ['Gama de scule', 'Compactă', 'Cea mai largă'],
        ],
      },
      {
        kind: 'compare',
        title: 'AMPShare vs M18',
        head: ['', 'Bosch Professional 18V (AMPShare)', 'Milwaukee M18'],
        rows: [
          ['Tip', 'Alianță de acumulatori între mai mulți producători', 'Sistemul propriu Milwaukee'],
          ['Compatibilitate', 'Același acumulator în sculele producătorilor din alianță', 'Toate sculele M18'],
          ['Gama', 'Scule Bosch Professional și ale partenerilor', 'Sute de scule M18, inclusiv linia de performanță FUEL'],
          ['Platformă compactă', 'Bosch Professional 12V (sistem separat)', 'M12 (sistem separat)'],
        ],
        note: 'Ambele sunt platforme mature, pentru uz profesional. Alege-o pe cea care acoperă sculele de care ai nevoie — și rămâi pe ea.',
      },
      { kind: 'carousel', title: 'Scule pe 18 V', text: 'Mașini de găurit, rotopercutoare, polizoare, fierăstraie.', subs: ['Sistemul de 18 V'] },
      { kind: 'carousel', title: 'Scule pe 12 V', text: 'Compacte, pentru montaj și instalații.', subs: ['Sistemul de 12 V'] },
      {
        kind: 'rules',
        title: 'Reguli rapide',
        items: [
          { when: 'Faci mai ales înșurubări și găuri mici', then: '12 V — mai ușor, mai compact, suficient.' },
          { when: 'Găurești beton, polizezi, tai', then: '18 V, ideal cu motor fără perii.' },
          { when: 'Echipezi o echipă întreagă', then: 'O singură platformă pentru toți — acumulatorii circulă între scule.' },
          { when: 'Ai nevoie de autonomie, nu de putere', then: 'Un acumulator cu mai mulți Ah, nu o sculă mai mare.' },
        ],
      },
      { kind: 'carousel', title: 'Acumulatori și încărcătoare', text: 'Capacități diferite pentru aceeași platformă.', subs: ['Baterii & încărcătoare', 'Acumulatori', 'Seturi acumulator și încărcător', 'Încărcătoare'] },
      { kind: 'carousel', title: 'Scule cu motor fără perii', text: 'Mai multă putere și autonomie din același acumulator.', subs: ['Scule electrice cu motor fără perii'] },
      { kind: 'tip', text: 'Cumpără la început un set cu două acumulatori și un încărcător rapid — iar sculele următoare, fără acumulator („solo”). Iese mult mai ieftin.', by: TEAM },
      {
        kind: 'faq',
        items: [
          { q: 'Pot folosi un acumulator Bosch într-o sculă Milwaukee?', a: 'Nu — platformele nu sunt compatibile între ele. Un acumulator din alianța AMPShare merge însă în sculele tuturor producătorilor din alianță.' },
          { q: 'Contează Ah pentru putere?', a: 'În principal pentru autonomie. Acumulatorii mai mari pot livra și curent mai mare, util la sculele solicitante, dar puterea o dă mai ales scula.' },
        ],
      },
    ],
  },

  // ══ Proiecte ══════════════════════════════════════════════════════════════
  {
    slug: 'renovare-baie-lista-de-scule',
    type: 'proiect',
    profession: 'Renovare baie',
    title: 'Renovare baie: lista de scule',
    domain: 'Proiect · Renovare',
    headline: 'De la demolare la ultimul rost — sculele pentru fiecare etapă.',
    excerpt: 'Ce scule îți trebuie ca să renovezi o baie: demolare, instalații, hidroizolație, placare cu gresie și faianță, montaj.',
    metaTitle: 'Renovare baie: lista de scule pe etape | Zona Scule',
    metaDescription: 'Lista completă de scule pentru renovarea unei băi: demolare, instalații, hidroizolație, placare cu gresie și faianță, găurit și montaj obiecte sanitare.',
    sections: [
      {
        kind: 'howto',
        title: 'Etapele unei renovări de baie',
        steps: [
          { title: 'Demolare', text: 'Scoți faianța, gresia și obiectele sanitare vechi — cu ciocan rotopercutor și dălți late.' },
          { title: 'Instalații', text: 'Refaci traseele de apă, scurgere și electrice înainte de placare.' },
          { title: 'Hidroizolație', text: 'Aplici hidroizolația pe pardoseală și pe pereții din zona dușului, cu bandă la colțuri.' },
          { title: 'Trasare', text: 'Cu nivela laser, marchezi primul rând de faianță și pantele pardoselii.' },
          { title: 'Placare', text: 'Tai plăcile, aplici adezivul cu gletiera dințată, montezi cu distanțiere și sistem de nivelare.' },
          { title: 'Rosturi și montaj', text: 'Chituiești rosturile, găurești pentru accesorii și montezi obiectele sanitare.' },
        ],
      },
      { kind: 'carousel', title: 'Demolare', text: 'Ciocane rotopercutoare și de spargere.', subs: ['Ciocane rotopercutoare', 'Găurire și spargere'] },
      { kind: 'carousel', title: 'Dălți', text: 'Late pentru faianță, plate și ascuțite pentru șape și zidărie.', subs: ['Dălți late', 'Dălți plate', 'Dălți ascuțite'] },
      {
        kind: 'checklist',
        title: 'Lista de scule',
        items: [
          { name: 'Ciocan rotopercutor SDS-plus', why: 'Demolare și găuri pentru instalații.', q: 'ciocan rotopercutor' },
          { name: 'Daltă lată', why: 'Scoate faianța fără să distrugă peretele.', q: 'dalta lata' },
          { name: 'Nivelă laser cu linii în cruce', why: 'Primul rând de faianță, drept.', q: 'nivela laser' },
          { name: 'Disc diamantat pentru gresie', why: 'Tăieturi drepte și decupaje.', q: 'disc diamantat gresie' },
          { name: 'Burghie pentru gresie', why: 'Găuri pentru accesorii, fără ciobiri.', q: 'burghiu gresie' },
          { name: 'Gletieră dințată și spaclu', why: 'Adezivul întins uniform.', q: 'gletiera' },
        ],
      },
      { kind: 'carousel', title: 'Tăiere gresie și faianță', text: 'Discuri diamantate și clești pentru plăci.', subs: ['Discuri de tăiere diamantate', 'Clește de tăiat - Nivelare placi'] },
      { kind: 'carousel', title: 'Găuri prin plăci ceramice', text: 'Pentru accesorii, baterii și trecerile țevilor.', subs: ['Burghie pentru plăci ceramice', 'Burghie diamantate'] },
      { kind: 'carousel', title: 'Gletiere, spacluri și mistrii', text: 'Pentru adeziv, șapă și chit de rosturi.', subs: ['Gletiere și spacluri', 'Spatule - Mistrii - Mașini de șlefuit manuale'] },
      { kind: 'carousel', title: 'Trasare', text: 'Nivele laser și cu bulă.', subs: ['Nivele laser cu linii în cruce', 'Nivele'] },
      { kind: 'tip', text: 'Găurește faianța deja montată fără percuție, pornind cu turație mică și cu o bucată de bandă de hârtie pe placă — burghiul nu alunecă și nu ciupește glazura.', by: TEAM },
    ],
  },
  {
    slug: 'montaj-gips-carton-pas-cu-pas',
    type: 'proiect',
    profession: 'Gips-carton',
    title: 'Montaj gips-carton pas cu pas',
    domain: 'Proiect · Compartimentări și tavane',
    headline: 'Pereți drepți și rosturi invizibile — cu sculele potrivite.',
    excerpt: 'Etapele montajului de pereți și tavane din gips-carton și sculele pentru fiecare: trasare, structură, placare, rosturi și finisaj.',
    metaTitle: 'Montaj gips-carton pas cu pas: etape și scule | Zona Scule',
    metaDescription: 'Cum montezi pereți și tavane din gips-carton: trasarea cu nivela laser, structura din profile, placarea, rosturile și finisajul — și sculele pentru fiecare etapă.',
    sections: [
      {
        kind: 'howto',
        title: 'Etapele montajului',
        steps: [
          { title: 'Trasare', text: 'Cu nivela laser, trasezi pe pardoseală, tavan și pereți poziția profilelor.' },
          { title: 'Profile de contur', text: 'Fixezi profilele UW/UD cu dibluri, la distanța indicată de sistem.' },
          { title: 'Structura', text: 'Montezi profilele CW/CD — de obicei la 60 cm, la 40 cm pentru plăci grele sau placare dublă.' },
          { title: 'Placare', text: 'Înșurubezi plăcile cu șuruburi pentru gips-carton, la 25 cm pe margini și în câmp.' },
          { title: 'Rosturi', text: 'Aplici bandă de armare și chit pe rosturi și pe capetele șuruburilor.' },
          { title: 'Finisaj', text: 'Șlefuiești fin, aspiri praful și aplici amorsa înainte de vopsire.' },
        ],
      },
      { kind: 'carousel', title: 'Trasare', text: 'Nivele laser cu linii în cruce și 360°.', subs: ['Nivele laser cu linii în cruce', 'Nivele laser'] },
      { kind: 'carousel', title: 'Înșurubare', text: 'Înșurubătoare cu acumulator, rapide și ușoare.', subs: ['Șurubelnițe cu impact cu acumulator', 'Maşini de găurit/înşurubat cu acumulator'] },
      {
        kind: 'checklist',
        title: 'Lista de scule',
        items: [
          { name: 'Nivelă laser 360°', why: 'Trasezi toată încăperea dintr-o poziție.', q: 'nivela laser' },
          { name: 'Mașină de găurit-înșurubat', why: 'Dibluri pentru profile și șuruburi în plăci.', q: 'masina de gaurit' },
          { name: 'Biți PH2', why: 'Profilul standard pentru șuruburile de gips-carton.', q: 'bit PH2' },
          { name: 'Cuțit cu lamă', why: 'Tăiat plăcile — crestezi, rupi, tai cartonul.', q: 'cutit' },
          { name: 'Spaclu și gletieră', why: 'Chit pe rosturi și finisaj.', q: 'spaclu' },
          { name: 'Aspirator', why: 'Praful fin de la șlefuire.', q: 'aspirator' },
        ],
      },
      { kind: 'carousel', title: 'Biți și adaptoare', text: 'PH2 și adaptoare cu limitator de adâncime.', subs: ['Capete de șurubelniță', 'Biți și adaptoare'] },
      { kind: 'carousel', title: 'Cuțite și lame', text: 'Pentru tăiatul plăcilor și al izolației.', subs: ['Cuțite și lame', 'Cuţite'] },
      { kind: 'carousel', title: 'Finisaj', text: 'Spacluri, gletiere și șlefuitoare.', subs: ['Gletiere și spacluri', 'Şlefuitoare cu excentric', 'Foi abrazive'] },
      { kind: 'carousel', title: 'Aspirarea prafului', text: 'Praful de gips e fin — aspirator cu filtru potrivit.', subs: ['Extractoare praf & aspiratoare', 'Aspiratoare umed-uscat (NT)'] },
      { kind: 'tip', text: 'Șuruburile trebuie să intre cu capul puțin sub carton, fără să-l rupă. Un adaptor cu limitator de adâncime face asta la fiecare șurub, fără efort.', by: TEAM },
    ],
  },
  {
    slug: 'terasa-din-lemn-scule',
    type: 'proiect',
    profession: 'Terasă din lemn',
    title: 'Terasă din lemn: scule și etape',
    domain: 'Proiect · Exterior',
    headline: 'O structură la nivel, scânduri drepte și șuruburi care nu ruginesc.',
    excerpt: 'Etapele construirii unei terase din lemn și sculele pentru fiecare: fundație, structură, tăiere, fixare și finisaj.',
    metaTitle: 'Terasă din lemn: etape și lista de scule | Zona Scule',
    metaDescription: 'Cum construiești o terasă din lemn: fundația și structura la nivel, tăierea și fixarea scândurilor, finisajul — și sculele de care ai nevoie la fiecare etapă.',
    sections: [
      {
        kind: 'howto',
        title: 'Etapele construcției',
        steps: [
          { title: 'Trasare și fundație', text: 'Marchezi conturul, nivelezi terenul și montezi suporturile sau plăcuțele reglabile.' },
          { title: 'Structura', text: 'Montezi grinzile la nivel, cu o pantă ușoară (în jur de 1–2%) pentru scurgerea apei.' },
          { title: 'Tăiere', text: 'Tai scândurile la lungime, cu îmbinările pe grinzi.' },
          { title: 'Fixare', text: 'Prinzi scândurile cu șuruburi din inox, cu găuri pre-date la capete și rosturi de 5–7 mm.' },
          { title: 'Finisaj', text: 'Șlefuiești capetele și aplici ulei sau lac pentru exterior.' },
        ],
      },
      { kind: 'carousel', title: 'Fierăstraie și scule pentru lemn', text: 'Circulare, de retezat și pendulare.', subs: ['Prelucrarea lemnului'] },
      { kind: 'carousel', title: 'Pânze pentru lemn', text: 'Pentru tăieri drepte și precise în scânduri și grinzi.', subs: ['Pânze de ferăstrău circular pentru lemn', 'Pânze de ferăstrău circular'] },
      {
        kind: 'checklist',
        title: 'Lista de scule',
        items: [
          { name: 'Fierăstrău circular sau de retezat', why: 'Tăieturi drepte la lungime.', q: 'ferastrau circular' },
          { name: 'Mașină de găurit-înșurubat', why: 'Găuri pre-date și șuruburi.', q: 'masina de gaurit' },
          { name: 'Burghie pentru lemn', why: 'Găuri la capete, ca scândurile să nu crape.', q: 'burghie lemn' },
          { name: 'Nivelă de 1–2 m', why: 'Structura la nivel, cu panta corectă.', q: 'nivela' },
          { name: 'Șlefuitor cu excentric', why: 'Capete și muchii netede înainte de ulei.', q: 'slefuitor excentric' },
        ],
      },
      { kind: 'carousel', title: 'Găurire și înșurubare', text: 'Mașini cu acumulator și înșurubătoare cu impact.', subs: ['Maşini de găurit/înşurubat cu acumulator', 'Șurubelnițe cu impact cu acumulator'] },
      { kind: 'carousel', title: 'Burghie pentru lemn', text: 'Cu vârf de centrare și lungi.', subs: ['Burghie pentru lemn'] },
      { kind: 'carousel', title: 'Nivele și măsură', text: 'Pentru structura la nivel și panta corectă.', subs: ['Nivele', 'Instrumente masura'] },
      { kind: 'carousel', title: 'Șlefuire', text: 'Șlefuitoare cu excentric și discuri abrazive.', subs: ['Şlefuitoare cu excentric', 'Discuri de șlefuit'] },
      { kind: 'tip', text: 'Folosește doar șuruburi din inox pentru exterior: cele zincate reacționează cu taninurile din lemn, lasă pete negre și ruginesc.', by: TEAM },
    ],
  },
  {
    slug: 'dotarea-unui-atelier-nou',
    type: 'proiect',
    profession: 'Atelier nou',
    title: 'Dotarea unui atelier nou',
    domain: 'Proiect · Atelier',
    headline: 'Ce cumperi întâi, ce poate aștepta — și cum organizezi totul.',
    excerpt: 'Lista de dotare pentru un atelier nou: bancul de lucru și menghina, sculele de mână, platforma de scule electrice, polizorul de banc, aspirarea și depozitarea.',
    metaTitle: 'Dotarea unui atelier nou: lista de scule | Zona Scule',
    metaDescription: 'Ce scule îți trebuie într-un atelier nou: menghină, truse de scule de mână, scule electrice pe o singură platformă de acumulatori, polizor de banc, aspirator, depozitare și protecție.',
    sections: [
      {
        kind: 'intro',
        lead: 'Un atelier bun nu se cumpără dintr-o dată. Începi cu ce folosești zilnic — bancul, menghina, sculele de mână și o platformă de scule electrice — și adaugi pe măsură ce apar lucrările.',
        steps: [
          { title: 'Baza', text: 'Banc de lucru, menghină, truse de chei și șurubelnițe.' },
          { title: 'Scule electrice', text: 'O singură platformă de acumulatori pentru mașina de găurit, polizor și restul.' },
          { title: 'Organizare și siguranță', text: 'Depozitare, aspirator și echipament de protecție.' },
        ],
      },
      { kind: 'carousel', title: 'Menghine', text: 'Prinderea sigură pe care se bazează tot restul.', subs: ['Menghine'] },
      { kind: 'carousel', title: 'Truse și chei', text: 'Seturi complete de scule de mână și chei combinate.', subs: ['Seturi și truse de scule', 'Chei combinate'] },
      {
        kind: 'checklist',
        title: 'Ordinea de cumpărare',
        items: [
          { name: 'Menghină', why: 'Prima dotare — pe ea se face orice lucrare.', q: 'menghina' },
          { name: 'Trusă de scule de mână', why: 'Chei, tubulare, șurubelnițe într-un singur set.', q: 'trusa scule' },
          { name: 'Set pe acumulator', why: 'Mașină de găurit și polizor pe aceeași platformă.', q: 'set combinat' },
          { name: 'Polizor de banc', why: 'Ascuțit, debavurat, ajustat.', q: 'polizor de banc' },
          { name: 'Aspirator umed-uscat', why: 'Atelier curat, praf sub control.', q: 'aspirator' },
          { name: 'Dulap sau sistem modular', why: 'Fiecare sculă are locul ei.', q: 'dulap scule' },
        ],
      },
      { kind: 'carousel', title: 'Seturi pe acumulator', text: 'Două sau mai multe scule cu acumulatori și încărcător comun.', subs: ['Seturi combinate', 'Sistemul de 18 V'] },
      { kind: 'carousel', title: 'Pentru polizorul de banc', text: 'Discuri pentru ascuțire și ajustaj.', subs: ['Discuri pentru Polizor de Banc'] },
      { kind: 'carousel', title: 'Aspirare', text: 'Aspiratoare umed-uscat pentru atelier.', subs: ['Aspiratoare umed-uscat (NT)'] },
      { kind: 'carousel', title: 'Depozitare', text: 'Dulapuri metalice și sisteme modulare.', subs: ['TOOLGUARD™ Sistem de depozitare metalic', 'PACKOUT™'] },
      { kind: 'carousel', title: 'Protecție', text: 'Ochelari, antifoane și mănuși — de la prima zi.', subs: ['Protecția ochilor', 'Protecție auditivă', 'Mănuși de protecție'] },
      { kind: 'tip', text: 'Pune sculele folosite zilnic la înălțimea mâinii, pe un panou sau în sertarele de sus — ce folosești rar poate sta jos sau sus. Un atelier ordonat e unul în care nu cauți.', by: TEAM },
    ],
  },
]
